functions:
  - name: add_days
    description: calculates a date by adding the specified number of days
    arguments:
      - name: datetime
        data_type: timestamp
        description: the datetime to add days to
      - name: days
        data_type: integer
        description: the number of days to add
    returns:
      data_type: timestamp

  - name: cents_to_dollars
    description: converts a currency value in cents to dollars
    arguments:
      - name: cents
        data_type: int
        description: the amount in cents
    returns:
      data_type: numeric(16, 2)
      description: the amount in dollars

  - name: cents_to_dollars_rounded
    description: converts a currency value in cents to dollars and rounds to the nearest dollar
    arguments:
      - name: cents
        data_type: int
        description: the amount in cents
    returns:
      data_type: numeric(16, 2)
      description: the amount in dollars