functions:
  - name: is_positive_int # required
    description: My UDF that determines if a string represents a positive (+) integer # required
    config:
      schema: udf_schema
      database: udf_db
    arguments: # optional
      - name: a_string # required if arguments is specified
        data_type: string # required if arguments is specified
        description: The string that I want to check if it's representing a positive integer (like "10") 
    returns: # required
      data_type: boolean # required
